apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-cm" (include "common.names.fullname" .) }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
data:
  metacat-config.json:
    '{
      "metacat.plugin.config.location" : "{{ .Values.catalogs.path }}",
      "metacat.usermetadata.config.location" : "/etc/metacat/usermetadata.properties"
    }'
  usermetadata.properties: |-
    javax.jdo.option.url=jdbc:mysql://{{ .Values.catalogs.userMetadata.dbHost }}:3306/metacat?useUnicode=true&characterEncoding=latin1&autoReconnect=true&sessionVariables=@@innodb_lock_wait_timeout=120&rewriteBatchedStatements=true
    javax.jdo.option.username=metacat_user
    javax.jdo.option.password=metacat_user_password
    javax.jdo.option.defaultTransactionIsolation=READ_COMMITTED
    javax.jdo.option.defaultAutoCommit=false
