auth:
  rootPassword: "root_password"
  database: "metacat"
  username: "metacat_user"
  password: "metacat_user_password"
initdbScripts:
  metacat.sql: |-
    SELECT 'GRANTING ALL TO metacat_user' as 'INFO';
    GRANT ALL ON *.* TO 'metacat_user'@'%' ;
    SELECT 'FINISHED GRANTING ALL TO metacat_user' as 'INFO';
    USE metacat;
    DROP TABLE IF EXISTS `data_metadata`;
    CREATE TABLE `data_metadata` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `version` bigint(20) NOT NULL,
    `created_by` varchar(255) NOT NULL,
    `data` longtext NOT NULL,
    `date_created` datetime NOT NULL,
    `last_updated` datetime NOT NULL,
    `last_updated_by` varchar(255) NOT NULL,
    `uri` varchar(4000) NOT NULL DEFAULT '',
    PRIMARY KEY (`id`),
    KEY `uri` (`uri`(767))
    );
    DROP TABLE IF EXISTS `data_metadata_delete`;
    -- Create schema for TABLE 'data_metadata_delete'
    CREATE TABLE data_metadata_delete (
    id bigint(20) NOT NULL,
    created_by varchar(255) NOT NULL,
    date_created datetime NOT NULL,
    PRIMARY KEY (id),
    KEY date_created (date_created)
    ) DEFAULT CHARSET=latin1;

    --
    -- Table structure for table `definition_metadata`
    --

    DROP TABLE IF EXISTS `definition_metadata`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `definition_metadata` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `version` bigint(20) NOT NULL,
    `created_by` varchar(255) NOT NULL,
    `data` longtext NOT NULL,
    `date_created` datetime NOT NULL,
    `last_updated` datetime NOT NULL,
    `last_updated_by` varchar(255) NOT NULL,
    `name` varchar(255) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `name` (`name`)
    ) ENGINE=InnoDB AUTO_INCREMENT=10078235 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    DROP TABLE IF EXISTS `partition_definition_metadata`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `partition_definition_metadata` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `version` bigint(20) NOT NULL,
    `created_by` varchar(255) NOT NULL,
    `data` longtext NOT NULL,
    `date_created` datetime NOT NULL,
    `last_updated` datetime NOT NULL,
    `last_updated_by` varchar(255) NOT NULL,
    `name` varchar(255) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `name` (`name`)
    ) ENGINE=InnoDB AUTO_INCREMENT=10078235 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;


    --
    -- Table structure for table `lookup`
    --

    DROP TABLE IF EXISTS `lookup`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `lookup` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `version` bigint(20) NOT NULL,
    `created_by` varchar(255) NOT NULL,
    `date_created` datetime NOT NULL,
    `last_updated` datetime NOT NULL,
    `last_updated_by` varchar(255) NOT NULL,
    `name` varchar(255) NOT NULL,
    `type` varchar(255) NOT NULL,
    `value` varchar(4000) NOT NULL DEFAULT '',
    PRIMARY KEY (`id`),
    UNIQUE KEY `name` (`name`)
    ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `lookup_values`
    --

    DROP TABLE IF EXISTS `lookup_values`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `lookup_values` (
    `lookup_id` bigint(20) DEFAULT NULL,
    `values_string` varchar(255) DEFAULT NULL,
    KEY `lookup_values_fk_looup_id` (`lookup_id`),
    CONSTRAINT `lookup_values_fk_looup_id` FOREIGN KEY (`lookup_id`) REFERENCES `lookup` (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `tag_item`
    --

    DROP TABLE IF EXISTS `tag_item`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `tag_item` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `version` bigint(20) NOT NULL,
    `created_by` varchar(255) NOT NULL,
    `date_created` datetime NOT NULL,
    `last_updated` datetime NOT NULL,
    `last_updated_by` varchar(255) NOT NULL,
    `name` varchar(255) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `name` (`name`)
    ) ENGINE=InnoDB AUTO_INCREMENT=99617 DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Table structure for table `tag_item_tags`
    --

    DROP TABLE IF EXISTS `tag_item_tags`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `tag_item_tags` (
    `tag_item_id` bigint(20) DEFAULT NULL,
    `tags_string` varchar(255) NOT NULL DEFAULT '',
    KEY `tag_item_tags_fk` (`tag_item_id`),
    KEY `tags_string` (`tags_string`),
    CONSTRAINT `tag_item_tags_fk` FOREIGN KEY (`tag_item_id`) REFERENCES `tag_item` (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;


