{{ if .Values.gke.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gke.ui.name}}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
  type: LoadBalancer
  loadBalancerIP: {{ .Values.gke.ui.ip }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
{{- end}}
